behaviors:
  CurriculumAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 512
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 20000000
    time_horizon: 128
    summary_freq: 20000
    threaded: true
environment_parameters:
  field_size:
    curriculum:
      - name: Size5Field
        completion_criteria:
          measure: reward
          behavior: CurriculumAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.6
        value: 5.0
      - name: Size6Field
        completion_criteria:
          measure: reward
          behavior: CurriculumAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.6
        value: 6.0
      - name: Size7Field
        completion_criteria:
          measure: reward
          behavior: CurriculumAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.6
        value: 7.0
      - name: Size8Field
        completion_criteria:
          measure: reward
          behavior: CurriculumAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.6
        value: 8.0
      - name: Size9Field
        completion_criteria:
          measure: reward
          behavior: CurriculumAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.6
        value: 9.0
      - name: Size10Field
        value: 10.0